# Generated by Django 4.2.20 on 2025-04-16 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appeventor', '0014_inquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fakepayment',
            name='event',
        ),
    ]
